DIM-12345

diff --git a/.github/workflows/target_workflow.yml b/.github/workflows/target_workflow.yml
--- a/.github/workflows/target_workflow.yml
+++ b/.github/workflows/target_workflow.yml
@@ -21,7 +21,7 @@ jobs:
 
       - name: Successful Step
         run: echo "This step is successful"
-      # - name: Failing Step
-      #   run: exit 1  # Deliberately fail this step
+      - name: Failing Step
+        run: exit 1  # Deliberately fail this step
       - name: Another Successful Step
         run: echo "This step is also successful"I     
