DIM-12345

diff --git a/.github/workflows/target_workflow.yml b/.github/workflows/target_workflow.yml
--- a/.github/workflows/target_workflow.yml
+++ b/.github/workflows/target_workflow.yml
@@ -19,11 +19,15 @@ jobs:
           echo ${{ github.event.client_payload.github.actor }}
           echo '{"github": ${{ toJson(github) }}}'
 
-      - name: Successful Step
-        run: echo "This step is successful"
-      # - name: Failing Step
-      #   run: exit 1  # Deliberately fail this step
-      - name: Another Successful Step
+      - name: Successful Step 1 
+        run: echo "This step is successful1"
+      - name: Another Successful Step 2 with wait time 100s
         run: |
-          echo "This step is also successful"  
+          echo "This step is also successful2"  
           sleep 100s 
+      - name: Failing Step 1
+        run: |
+          exit 1  # Deliberately fail this step
+      - name: Successful Step 3  
+        run: echo "This step is successful3"
+
