DIM-12345

diff --git a/.github/workflows/target_workflow.yml b/.github/workflows/target_workflow.yml
--- a/.github/workflows/target_workflow.yml
+++ b/.github/workflows/target_workflow.yml
@@ -24,10 +24,10 @@ jobs:
       - name: Another Successful Step 2 with wait time 100s
         run: |
           echo "This step is also successful2"  
-          sleep 100s 
-      - name: Failing Step 1
-        run: |
-          exit 1  # Deliberately fail this step
+          sleep 20s 
+      # - name: Failing Step 1
+      #   run: |
+      #     exit 1  # Deliberately fail this step
       - name: Successful Step 3  
         run: echo "This step is successful3"
 
